services:
  db:
    profiles: ["core"]
    image: pgvector/pgvector:pg16
    container_name: cobalt_memory
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - cobalt_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: cobalt_viewer
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "18080:80"
    restart: always
    networks:
      - cobalt_net
    depends_on:
      - db

  mattermost:
    profiles: ["core"]
    image: mattermost/mattermost-enterprise-edition:latest
    platform: linux/amd64
    ports:
      - "8065:8065"
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable&connect_timeout=10
    depends_on:
      - db
    volumes:
      - mattermost_config:/mattermost/config
      - mattermost_data:/mattermost/data
    restart: unless-stopped
    networks:
      - cobalt_net

networks:
  cobalt_net:
    driver: bridge

volumes:
  mattermost_config:
  mattermost_data:
