services:
  db:
    image: pgvector/pgvector:pg16
    container_name: cobalt_memory
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - cobalt_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: cobalt_viewer
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "18080:80"
    networks:
      - cobalt_net
    depends_on:
      - db

networks:
  cobalt_net:
    driver: bridge